# Generated by Django 3.2.8 on 2022-11-05 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.location', verbose_name='Location'),
            preserve_default=False,
        ),
    ]
