# Generated by Django 3.2.8 on 2022-11-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_classroom_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_unit', models.CharField(max_length=255, verbose_name='Group unit')),
            ],
            options={
                'verbose_name': 'GroupUnit',
                'verbose_name_plural': 'GroupUnits',
                'ordering': ('group_unit',),
            },
        ),
    ]
